# Generated by Django 3.0.5 on 2020-05-27 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='aurthor',
            new_name='author',
        ),
    ]
